#!/bin/bash
set -e

source VERSION

GITREMOTE=$(git config --get remote.origin.url)
GITHOST=$(echo "${GITREMOTE}" | sed -r "s|((.*)(\:\/\/))?((.*)\@)?([^\/:]*)(\:([0-9]+))?[:\/](.*)(\.git)|\6|")
GITPATH=$(echo "${GITREMOTE}" | sed -r "s|((.*)(\:\/\/))?((.*)\@)?([^\/:]*)(\:([0-9]+))?[:\/](.*)(\.git)|\9|")

docker image build --pull \
--tag ${DOCKER_REPO}:${DOCKER_TAG} \
--build-arg ALPINE_VERSION=${ALPINE_VERSION} \
--label org.opencontainers.image.created="$(date -u +"%Y-%m-%dT%H:%M:%S%Z_%Z")" \
--label org.opencontainers.image.revision="$(git rev-parse --short HEAD)" \
--label org.opencontainers.image.version="$(git describe --abbrev=0 --tags 2>/dev/null)" \
--label org.opencontainers.image.title="$(basename ${PWD})" \
--label org.opencontainers.image.vendor="firecyberice" \
--label org.opencontainers.image.source="https://${GITHOST}/${GITPATH}" \
.
